# Generated by Django 5.0.6 on 2024-07-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listings',
            new_name='listing',
        ),
    ]
